module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                secondary: "#CCCCCC",
                primary: "#E6E6E6",
                inactive: "#BFBFBF",
                darkGray: "#4D4D4D",
                hover: "#FFF",
                hoverSocial: "#FFF",
                accent1: "#ff7044",
                accent2: "#ffbbd8",
                accent3: "#004d3f",
                accent4: "#fbd599",
                accent5: "#283cea",
                accent6: "#ffd941",
                accent7: "#ff9d82",
                accent8: "#a944ff",
                accent9: "#b1915e",
                accent10: "#aa7fff",
                accent11: "#ff4d29",
                accent12: "#623d52",
                accent13: "#edff44",
                accent14: "#5d5f30",
                accent15: "#1f3142",
                accent16: "#917531",
                accent17: "#7ea8fd",
                accent18: "#5a44ff",
                accent19: "#ffffff",
                accent20: "#000000",
                bgColor1: "#b7cae7",
                bgColor2: "#f7ce7e",
                bgColor3: "#bb9395",
                bgColor4: "#fbd599",
                bgColor5: "#99a37d",
                bgColor6: "#ffc58c",
                bgColor7: "#ccd6ad",
                bgColor8: "#ed9c6a",
            },
            fontFamily: {
                relative: "relative-medium-pro",
            },
        },
    },
    plugins: [],
};
