module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                secondary: "#CCCCCC",
                primary: "#E6E6E6",
                inactive: "#BFBFBF",
                darkGray: "#4D4D4D",
                hover: "#FFF",
                hoverSocial: "#FFF",
                accent1: "#f97612",
                accent2: "#ffbbd8",
                accent3: "#004d3f",
                accent4: "#fbd599",
                accent5: "#283cea",
                accent6: "#ffe44e",
                accent7: "#ff9d82",
                accent8: "#e69dd4",
                accent9: "#ecb553",
                accent10: "#f61918",
                accent11: "#ff4d29",
                accent12: "#623d52",
                accent13: "#edff44",
                accent14: "#5d5f30",
                accent15: "#005d7f",
                accent16: "#b363b6",
                accent17: "#7ea8fd",
                accent18: "#39a46b",
                accent19: "#ffffff",
                accent20: "#000000",
            },
            fontFamily: {
                relative: "relative-medium-pro",
            },
        },
    },
    plugins: [],
};
